animalwellbeing/urls.py
from django.urls import path
from . import views
app_name = 'awb'
urlpatterns = [
    path('', views.index, name='index'),
    path('awb/', views.index, name='index'),
    path('awb/accounts/login', views.login_view, name='login'),
    path('awb/accounts/logout',views.logout_view, name='logout'),
    path('awb/createcoversheet',views.form_creation, name='createcoversheet'),
    path('awb/accounts/createresearcher', views.create_researcher, name='create_researcher'),
    path('awb/download/<int:coversheet_id>/', views.download_cs, name='download'),
    path('awb/edit/<int:coversheet_id>/', views.edit_form, name='edit_cs'),
    path('awb/search', views.search, name='search'),
    path('awb/user_activation', views.user_activation, name='user_activation'),
    path('awb/activate/<str:username>', views.activate, name='activate'),
    path('awb/profile', views.view_profile, name='view_profile'),
    path('awb/edit_profile', views.edit_profile, name='edit_profile'),
    path('awb/change_password', views.change_password, name='change_password'),
    path('awb/get_username', views.get_username, name='get_username'),
    path('awb/validate_question', views.validate_question, name='validate_question'),
    path('awb/panel/<int:coversheet_id>/', views.panel, name='panel_cs'),
    path('awb/approve_or_disapprove_coversheet/<int:coversheet_id>/', views.approve_or_disapprove_coversheet, name='approve_or_disapprove_cs'),
    path('awb/request_approval/<int:coversheet_id>/', views.request_approval, name='request_approval'),
    path('awb/cs_requests/',views.requests_approval_admin, name='cs_requests'),
    path('awb/cancel_request/<int:coversheet_id>/', views.cancel_request, name='cancel_request'),
    path('awb/activate_detail/<str:username>/', views.activate_detail, name='activate_detail'),
    path('awb/decline_user/<str:username>/',views.decline_user,name='decline_user'),
    path('awb/criteria', views.criteria, name='criteria')
]

testsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('animalwellbeing.urls')),
]

animalwellbeing/forms.py
from django import forms


class LoginForm(forms.Form):
    Username = forms.CharField(max_length=30)
    Password = forms.CharField(max_length=30)


class SignUpForm(forms.Form):
    Username = forms.CharField(max_length=30)
    Password = forms.CharField(max_length=30)
    First_Name = forms.CharField(max_length=30)
    Surname = forms.CharField(max_length=30)
    Email = forms.EmailField(max_length=100)
    Question = forms.CharField(max_length=150)
    Answer = forms.CharField(max_length=50)


class ReviewForm(forms.Form):
	comment = forms.CharField(max_length=300,widget=forms.Textarea)

class CoverSheetForm(forms.Form):
    aec_protocol = forms.CharField(max_length=200, strip=False)
    protocol_title = forms.CharField(max_length=200, strip=False)
    start_date = forms.DateField()
    cheif_investigator = forms.CharField(max_length=30)
    cheif_investigator_phone = forms.CharField(max_length=10)
    emergency_investigator = forms.CharField(max_length=30)
    emergency_investigator_phone = forms.CharField(max_length=10)
    monitor_1 = forms.CharField(max_length=30)
    monitor_1_phone = forms.CharField(max_length=10)
    monitor_2 = forms.CharField(max_length=30)
    monitor_2_phone = forms.CharField(max_length=10)
    monitor_3 = forms.CharField(max_length=30)
    monitor_3_phone = forms.CharField(max_length=10)
    supervision = forms.BooleanField()
    euthanasia_person = forms.CharField(max_length=30)
    euthanasia_phone = forms.CharField(max_length=10)
    other_experts = forms.CharField(max_length=30)
    other_experts_phone = forms.CharField(max_length=10)
    # species/phenotype/issues
    species_phenotype_issues = forms.CharField(max_length=30)
    # MONITORING CRITERIA AND SCORING
    scrit = forms.CharField()
    pcrit = forms.CharField()

    # monitory frequency
    monitoring_frequency = forms.CharField(max_length=200)
    # type of recording sheet
    typeofsheet = forms.ChoiceField()
    other_description = forms.CharField()
    protocol_title = forms.CharField(max_length=200, strip=False)
    start_date = forms.DateTimeField()
    cheif_investigator = forms.CharField(max_length=30)
    cheif_investigator_phone = forms.CharField(max_length=10)
    emergency_investigator = forms.CharField(max_length=30)
    emergency_investigator_phone = forms.CharField(max_length=10)
    monitor_1 = forms.CharField(max_length=30)
    monitor_1_phone = forms.CharField(max_length=10)
    monitor_2 = forms.CharField(max_length=30)
    monitor_2_phone = forms.CharField(max_length=10)
    monitor_3 = forms.CharField(max_length=30)
    monitor_3_phone = forms.CharField(max_length=10)
    supervision = forms.BooleanField()
    euthanasia_person = forms.CharField(max_length=30)
    euthanasia_phone = forms.CharField(max_length=10)
    other_experts = forms.CharField(max_length=30)
    other_experts_phone = forms.CharField(max_length=10)
    #species/phenotype/issues
    species_phenotype_issues = forms.CharField(max_length=30)
    #MONITORING CRITERIA AND SCORING
    actions1a = forms.CharField()
    actions1b = forms.CharField()
    actions2a = forms.CharField()
    actions2b = forms.CharField()
    actions3a = forms.CharField()
    actions3b = forms.CharField()
    actions4a = forms.CharField()
    actions4b = forms.CharField()
    additional = forms.CharField()
    #AEC interventions
    aec1 = forms.CharField()
    aec2 = forms.CharField()
    aec3 = forms.CharField()
    aec4 = forms.CharField()
    aec5 = forms.CharField()
    aec6 = forms.CharField()
    aec7 = forms.CharField()
    aec8 = forms.CharField()
    #monitory frequency
    monitoring_frequency = forms.CharField(max_length=200,widget=forms.Textarea)
    #type of recording sheet
    general = forms.BooleanField()	
    anasthesia = forms.BooleanField()
    post_proc = forms.BooleanField()
    other = forms.BooleanField()
    other_description = forms.CharField()


class EditProfileForm(forms.Form):
    First_Name = forms.CharField(max_length=30)
    Surname = forms.CharField(max_length=30)
    Email = forms.EmailField(max_length=100)


class QuestionForm(forms.Form):
    Username = forms.CharField(max_length=30,  widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    Question = forms.CharField(max_length=150,  widget=forms.TextInput(attrs={'readonly': 'readonly', 'size': 80}))
    Answer = forms.CharField(max_length=50)
    Password = forms.CharField(max_length=30)

class CriteriaTemplateForm(forms.Form):
    name = forms.CharField()
    scrit = forms.CharField()

animalwellbeing/views.py
from django.shortcuts import render, redirect
# will improve later down the line
from .forms import *
from .models import *
from django.db.models import Q
from django.urls import reverse

# user authentication
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import PasswordChangeForm

# downloading files
from django.http import FileResponse
import subprocess
import json
# Create your views here.

from .additional_func import standardise_keys


def index(request):
	context = {}
	if request.user.is_authenticated and (
			request.user.is_superuser or Researchers.objects.filter(user=request.user).exists()):
		context = {
			'isResearcher': not request.user.is_superuser,
			'user': request.user if request.user.is_superuser else Researchers.objects.get(user=request.user),
			'templates': CoverSheetFormModel.objects.all().order_by(
				'-updated_at') if request.user.is_superuser else CoverSheetFormModel.objects.filter(
				creator=Researchers.objects.get(user=request.user)).order_by('-updated_at')
		}
	return redirect('/awb/accounts/login') if not request.user.is_authenticated else render(request,
																							'animalwellbeing/welcome.html',
																							context)


def logout_view(request):
	logout(request)
	return redirect('/awb/')


@login_required
@user_passes_test(lambda u: u.is_superuser)
def requests_approval_admin(request):
	context = {
		'user': request.user if request.user.is_superuser else Researchers.objects.get(user=request.user),
		'templates': CoverSheetFormModel.objects.filter(request_lodged=True).order_by('-updated_at')
	}
	return render(request, 'animalwellbeing/requests.html', context)


@login_required
def view_coversheet(request, coversheet_id):
	coversheetmodel = None
	try:
		# improve this later on
		coversheetmodel = CoverSheetFormModel.objects.get(pk=coversheet_id)
		return render(request, 'animalwellbeing/view_coversheet.html', coversheetmodel.all_data)
	except CoverSheetFormModel.DoesNotExist:
		return redirect('/awb/')


def password_validators(password):
	if len(password) < 6 or \
			all(char.isdigit() for char in password) or \
			all(char.isalpha() for char in password) or \
			all(char.islower() for char in password):
		return True


@login_required
def request_approval(request, coversheet_id):
	coversheetmodel = None
	try:
		if request.user.is_superuser:
			coversheetmodel = CoverSheetFormModel.objects.get(pk=coversheet_id)
		else:
			coversheetmodel = CoverSheetFormModel.objects.get(pk=coversheet_id,
															  creator=Researchers.objects.get(user=request.user))
		coversheetmodel.request_lodged = True
		coversheetmodel.save()
	except CoverSheetFormModel.DoesNotExist:
		pass
	return redirect('/awb/panel/{}/'.format(coversheet_id))


def create_researcher(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		username = form['Username'].value()
		password = form['Password'].value()
		email = form['Email'].value()
		surname = form['Surname'].value()
		firstname = form['First_Name'].value()
		input_question = form['Question'].value()
		input_answer = form['Answer'].value()
		try:
			user = User.objects.create_user(
					username=username,
					password=password,
					email=email,
					is_active=False
				)
			user.save()
			new_researcher = Researchers.objects.create(
					user=user,
					surname=surname,
					firstname=firstname,
					email=email
				)
			new_researcher.save()
			question = Question.objects.create(
					user_Q=username,
					Question=input_question,
					Answer=input_answer
				)
			question.save()
			print('Successfully created researcher')
		except:
			pass
		return redirect('/awb/')
	usernames = json.dumps([user.username for user in User.objects.all()])
	return render(request, 'animalwellbeing/signup.html',{'usernames':usernames})

def user_activation(request):
	context = {
		'is_active': User.objects.filter(is_active=False)
	}
	return render(request, 'animalwellbeing/activation.html', context)

@login_required
@user_passes_test(lambda u: u.is_superuser)
def activate(request, username):
	try:
		user_need_activation = User.objects.get(username=username)
		user_need_activation.is_active = True
		user_need_activation.save()
		context = {
			'is_active': User.objects.filter(is_active=False)
		}
		return render(request, 'animalwellbeing/activation.html', context)
	except User.DoesNotExist:
		return redirect('/awb/')
		


@login_required
def view_profile(request):
	user = request.user
	args = {'user': user}
	context = {'researchers_infor': Researchers.objects.get(user=user),
			   'user': request.user if request.user.is_superuser else Researchers.objects.get(user=request.user)}
	return render(request, 'animalwellbeing/profile.html', context, args)


@login_required
def edit_profile(request):
	if request.method == 'POST':
		form = EditProfileForm(request.POST)
		if form.is_valid():
			First_Name = form.cleaned_data['First_Name']
			Surname = form.cleaned_data['Surname']
			email = form.cleaned_data['Email']
			r = Researchers.objects.get(user=request.user)
			r.firstname = First_Name
			r.surname = Surname
			r.save()
			u = User.objects.get(username=request.user)
			u.email = email
			u.save()
			return redirect(reverse('awb:view_profile'))
	else:
		data = {'First_Name': Researchers.objects.get(user=request.user).firstname,
				'Surname': Researchers.objects.get(user=request.user).surname,
				'Email': User.objects.get(username=request.user).email}
		form = EditProfileForm(initial=data)
		args = {'form': form,
				'user': request.user if request.user.is_superuser else Researchers.objects.get(user=request.user)}
		return render(request, 'animalwellbeing/edit_profile.html', args)


@login_required
def change_password(request):
	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)

		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			return redirect(reverse('awb:view_profile'))

	else:
		form = PasswordChangeForm(user=request.user)

	args = {'form': form, 'user': request.user if request.user.is_superuser else Researchers.objects.get(user=request.user)}
	return render(request, 'animalwellbeing/change_password.html', args)


def get_username(request):
	if request.method == 'POST':
		username = request.POST.get('search_name')
		exist = User.objects.filter(username=username)
		if exist and username:
			data = {'Question': Question.objects.get(user_Q=username).Question,
					'Username': username}
			form = QuestionForm(initial=data)
			args = {'form': form}
			return render(request, 'animalwellbeing/validate_question.html', args)
		elif not exist:
			return render(request, 'animalwellbeing/get_username.html', {'attempt': True})
	return render(request, 'animalwellbeing/get_username.html')


def validate_question(request):
	if request.method == "POST":
		form = QuestionForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['Username']
			answer = form.cleaned_data['Answer']
			password = form.cleaned_data['Password']
			a = password_validators(password)
			if a:
				data = {'Question': Question.objects.get(user_Q=username).Question,
						'Username': username}
				form = QuestionForm(initial=data)
				data = {'first': "Your password must contain at least 6 characters",
						'second': "Your password must contain at least 1 uppercase letter",
						'third': "Your password must contain at least 1 number and 1 letter",
						'form': form}
				return render(request, 'animalwellbeing/validate_question.html', data)

			if answer == Question.objects.get(user_Q=username).Answer:
				user = User.objects.get(username=username)
				user.set_password(password)
				user.save()
				return redirect('/awb/accounts/login')
			else:
				data = {'Question': Question.objects.get(user_Q=username).Question,
						'Username': username}
				form = QuestionForm(initial=data)
				args = {'form': form, 'answer_wrong': "Your answer was incorrect, please try again"}
				return render(request, 'animalwellbeing/validate_question.html', args)
	return redirect('awb:get_username')


@login_required
def panel(request, coversheet_id):
	coversheetmodel = None
	try:
		if request.user.is_superuser:
			coversheetmodel = CoverSheetFormModel.objects.get(pk=coversheet_id)
		else:
			coversheetmodel = CoverSheetFormModel.objects.get(pk=coversheet_id,
															  creator=Researchers.objects.get(user=request.user))
	except CoverSheetFormModel.DoesNotExist:
		return redirect('/awb/')

	if request.method == 'POST':
		form = ReviewForm(request.POST)
		msg = Message.objects.create(message=form['comment'].value(), date=datetime.datetime.now(),
									 coversheet=coversheetmodel, author=request.user.username)
		coversheetmodel.request_lodged = False
		coversheetmodel.save()
		msg.save()

	return render(request, 'animalwellbeing/coversheetpanel.html', {
		'coversheet': coversheetmodel,
		'user': request.user if request.user.is_superuser else Researchers.objects.get(user=request.user),
		'messagelist': Message.objects.filter(coversheet=coversheetmodel).order_by('-date'),
	})


@login_required
def cancel_request(request, coversheet_id):
	coversheetmodel = None
	try:
		if request.user.is_superuser:
			coversheetmodel = CoverSheetFormModel.objects.get(pk=coversheet_id)
		else:
			coversheetmodel = CoverSheetFormModel.objects.get(pk=coversheet_id,
															  creator=Researchers.objects.get(user=request.user))
	except CoverSheetFormModel.DoesNotExist:
		return redirect('/awb/')
	coversheetmodel.request_lodged = False
	coversheetmodel.save()
	return redirect('/awb/panel/{}/'.format(coversheet_id))


@login_required
def edit_form(request, coversheet_id):
	criteriamodel = None
	coversheetmodel = None
	try:
		if request.user.is_superuser:

animalwellbeing/templates/animalwellbeing/activation-detail.html
{% extends "./index.html" %}
{% block title %} Activation Requests {% endblock %}
{% block content %}
<center><h1>User : {{user.user.username}}</h1></center>

	 <div class="container">
	 	<div class ="card"> 
        <div class="card-header">
<a href={% url 'awb:activate' username=usertoactivate.user.username  %}><button type="button" class="btn btn-outline-primary"> Activate User</button></a>
		<div class="float-sm-right"><a href={% url 'awb:decline_user' username=usertoactivate.user.username %}><button type="button" class="btn btn-outline-danger"> Decline Activation</button></a></div>
        </div>
        <div class="card-body">
        	<div class="container">
				<table class="table">
				  <tbody>
				    <tr>
				      <th scope="row">Firstname</th>
				      <td>{{usertoactivate.firstname}}</td>
				    </tr>
				    <tr>
				      <th scope="row">Surname</th>
				      <td>{{usertoactivate.surname}}</td>
				    </tr>
				    <tr>
				      <th scope="row">Username</th>
				      <td>{{usertoactivate.user.username}}</td>
				    </tr>
				    <tr>
				      <th scope="row">Email</th>
				      <td>{{usertoactivate.email}}</td>
				    </tr>
				  </tbody>
				</table>
			</div>
        </div>
    </div>
</div>

{% endblock %}

animalwellbeing/templates/animalwellbeing/coversheetpanel.html
{% extends "./index.html" %}

{% block title %} Coversheet {{coversheet.id}} Panel {% endblock %}
{% block content %}

<div class="container">
<center><h1>Coversheet {{coversheet.id}} Panel</h1></center>

<div class="card">
	<div class="card-header"> 			
		<a href={% url 'awb:edit_cs' coversheet.pk %}><button type="button" class="btn btn-outline-primary"> {% if request.user.is_superuser or coversheet.approved or coversheet.request_lodged %}View {% else %}Edit {% endif %}Coversheet</button></a>
		<div class="float-sm-right"><a href={% url 'awb:download' coversheet.pk %}><button type="button" class="btn btn-outline-primary"> Download Coversheet</button></a></div>
	</div>
	<br>
		<div class="class-body">
			<div class="container">
			{% if request.user.is_superuser  %}
				{% if not coversheet.approved %}
				<a href= {% url 'awb:approve_or_disapprove_cs' coversheet.pk %}><button type="button" class="btn btn-outline-success">Approve Coversheet</button></a>
				{% else %}
				<a href={% url 'awb:approve_or_disapprove_cs' coversheet.pk %}><button type="button" class="btn btn-outline-danger">Unapprove Coversheet</button></a>
				{% endif %}
				
				
			{% else %}
				{% if not coversheet.approved  %}
					{% if not coversheet.request_lodged %}
					<a href= {% url 'awb:request_approval' coversheet.pk %}><button type="button" class="btn btn-outline-danger">Request Approval</button></a>
					{% else %}
						Coversheet is currently under review with admin. Click <a href={% url 'awb:cancel_request' coversheet.pk %}>here</a>  to cancel request review
					{% endif %}
				{% endif %}
			{% endif %}
			</div>
			<br>
			<div class="container">
				<table class="table">
				  <tbody>
				    <tr>
				      <th scope="row">Title</th>
				      <td>{{coversheet.name}}</td>
				    </tr>
				    <tr>
				      <th scope="row">Created</th>
				      <td>{{coversheet.created_at}}</td>
				    </tr>
				    <tr>
				      <th scope="row">Last Updated</th>
				      <td>{{coversheet.updated_at}}</td>
				    </tr>
				    <tr>
				      <th scope="row">Author</th>
				      <td>{{coversheet.creator.firstname}} {{coversheet.creator.surname}}</td>
				    </tr>
				    <tr>
					  <th scope="row">Author Email</th>
				      <td>{{coversheet.creator.email}}</td>
				    </tr>
					 <tr>
				      <th scope="row">Approved</th>
				      <td>{% if coversheet.approved %} Yes {% else %} No {% endif %}</td>
				    </tr>
				    <tr>
				      <th scope="row">Request Made</th>
				      <td>{% if coversheet.request_lodged %} Yes {% else %} No {% endif %}</td>
				    </tr>

				  </tbody>
				</table>
			</div>
			
			{% if coversheet.approved  %}
			<div class="container">
				<a href={% url 'awb:download_rs' coversheet.pk %}><button type="button" class="btn btn-outline-success">Use for Recording Sheet</button></a>
				</div>
				<br>
			{% else %}
			{% if user.is_superuser and coversheet.request_lodged %}
			<div class="card">
				<div class="card-header"> Review </div>
				<div class="card-body">
					<form method="POST">
						{% csrf_token %}
						<textarea name="comment" class="form-control" ></textarea>
						<br>
						<button class="btn btn-outline-danger" type="submit"> Submit comment and decline request</button>
					</form>
				</div>
			</div>
			{% endif %}
			{% endif %}
			{% if messagelist %}
			<div class="card">
				<div class="card-header"> Review Messages </div>
				<div class="card-body">
					{% for msg in messagelist %}
						<b>{{msg.author}}:</b> <div class="float-sm-right"> <i>{{msg.date}} </i></div> <br>  <div style="padding-left:4em;">{{msg.message}}</div>
						<br>
					{% endfor %}
				</div>
			</div>
			{% endif %}

		</div>
	</div>
</div>

{% endblock %}

animalwellbeing/templates/animalwellbeing/edit_profile.html
{% extends "./index.html" %}
{% block title %} {% if request.user.is_superuser %} {{user.username}} {% else %} {{user.firstname}} {% endif %}'s Profile {% endblock %}
{% block content %}
    <br>
    <br>
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
            <p> If you would like to change your password, please click
            <a href={% url 'awb:change_password' %}> Here</a></p>
        </form>
        <br>
    </div>
{% endblock %}

animalwellbeing/templates/animalwellbeing/index.html
<!DOCTYPE html>
<html>
	
		<head>
				<title> {% block title %} {{user.username}}'s Profile {% endblock %} </title>
				<meta charset="utf-8">
				<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
			
				<!-- Bootstrap CSS -->
				<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
						
		</head>


		<nav class="navbar navbar-expand-md navbar-dark bg-dark">
			<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Coversheets
	        </a>
	        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
	          <a class="dropdown-item" href={% url 'awb:createcoversheet' %}>Create</a>
	          <a class="dropdown-item" href={% url 'awb:index' %}>View All</a>
	          {% if request.user.is_superuser %}
				<a class="dropdown-item" href={% url 'awb:cs_requests' %}>Requests</a>
	          {% endif %}
	          <div class="dropdown-divider"></div>
	          <a class="dropdown-item" href={% url 'awb:criteria' %}>Edit Criteria Settings</a>
	        </div>
	      </li>
        </ul>
    </div>
    <div class="mx-auto order-0">
    	{% load static %}
         <a class="navbar-brand mx-auto" href={% url 'awb:index' %}><img src= "{% static 'animalwellbeing/uwa-logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">TELOS</a>
       
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2 dropdown-pull-left">
    	{% load static %}
        <ul class="navbar-nav ml-auto">
        	 <li class="nav-item dropdown">
	         <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="margin-right: 1em;">{% if request.user.is_superuser %} <img src= "{% static 'animalwellbeing/adminprofile.png' %}" width="30" height="30" class="d-inline-block align-top" alt=""> {{user.username}}{% else %}<img src= "{% static 'animalwellbeing/profile.png' %}" width="30" height="30" class="d-inline-block align-top" alt=""> {{user.firstname}} {{user.surname}}{% endif %}</a>
	        <div class="dropdown-menu dropdown-pull-right" aria-labelledby="navbarDropdown">
            {% if request.user.is_superuser %}
            <a class="dropdown-item" href={% url 'awb:user_activation' %}>Researcher <br> Requests</a>
            {% endif %}
            {% if not request.user.is_superuser %}
            <a class="dropdown-item" href={% url 'awb:view_profile' %}> Profile </a>
            {% endif %}
	          <div class="dropdown-divider"></div>
	          <a class="dropdown-item" href={% url 'awb:logout' %}>
	          	<button type="button" class="btn btn-outline-danger">Logout</button></a>
	        </div>
	      </li>

        </ul>
    </div>
</nav>
  
<body>
	{% block content %}{% endblock %}
</body>
<br><br><br>
<center>
<p class="text-muted">If you are having troubles please contact your administrator or the Animal Ethics Office (6488 7887 / 3033) </p>
<br>
<p class="text-muted"> Click <a href="http://www.research.uwa.edu.au/staff/forms/animals">here</a> for more info</p>
</center>
<br><br><br>
<!-- Footer -->
	<!-- need to get it sorted -->
<!-- 	<center>
	<p class="text-muted" style="bottom: 0;
margin-top:1em;
  left: 0;
  text-align: center;
  position: absolute;
  width: 100%;
  height: 5em;
  ">For support please contact admin or your facilitator</p>
	</center> -->
<!-- <footer class="navbar-dark bg-dark d-inline-block" style="bottom: 0;
margin-top:1em;
  left: 0;
  text-align: center;
  position: relative;
  width: 100%;
  height: 4em;
  ">
    <center>
    	<div class="container">
      <font color="white">TELOS</font><br>
      <i><font color="white">Respecting the unique nature of each animal species</font></i>
  </div>
	</center>

  </footer> -->
  <!-- 
<footer style="bottom: 0;
  left: 0;
  position: fixed;
  text-align: center;
  width: 100%;
  height: 2em;
  z-index: -1;">
	stay at bottom
</footer> -->
  <!-- Footer -->
</html>