animalwellbeing/urls.py
from django.urls import path
from . import views
app_name = 'awb'
urlpatterns = [
    path('', views.index, name='index'),
    path('awb/', views.index, name='index'),
    path('awb/accounts/login', views.login_view, name='login'),
    path('awb/accounts/logout',views.logout_view, name='logout'),
    path('awb/createcoversheet',views.form_creation, name='createcoversheet'),
    path('awb/accounts/createresearcher', views.create_researcher, name='create_researcher'),
    path('awb/download/<int:coversheet_id>/', views.download_cs, name='download'),
    path('awb/edit/<int:coversheet_id>/', views.edit_form, name='edit_cs'),
    path('awb/search', views.search, name='search'),
    path('awb/user_activation', views.user_activation, name='user_activation'),
    path('awb/activate/<str:username>', views.activate, name='activate'),
    path('awb/profile', views.view_profile, name='view_profile'),
    path('awb/edit_profile', views.edit_profile, name='edit_profile'),
    path('awb/change_password', views.change_password, name='change_password'),
    path('awb/get_username', views.get_username, name='get_username'),
    path('awb/validate_question', views.validate_question, name='validate_question'),
    path('awb/panel/<int:coversheet_id>/', views.panel, name='panel_cs'),
    path('awb/approve_or_disapprove_coversheet/<int:coversheet_id>/', views.approve_or_disapprove_coversheet, name='approve_or_disapprove_cs'),
    path('awb/request_approval/<int:coversheet_id>/', views.request_approval, name='request_approval'),
    path('awb/cs_requests/',views.requests_approval_admin, name='cs_requests'),
    path('awb/cancel_request/<int:coversheet_id>/', views.cancel_request, name='cancel_request'),
    path('awb/activate_detail/<str:username>/', views.activate_detail, name='activate_detail'),
    path('awb/decline_user/<str:username>/',views.decline_user,name='decline_user'),
    path('awb/criteria', views.criteria, name='criteria')
]

testsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('animalwellbeing.urls')),
]

animalwellbeing/forms.py
from django import forms


class LoginForm(forms.Form):
    Username = forms.CharField(max_length=30)
    Password = forms.CharField(max_length=30)


class SignUpForm(forms.Form):
    Username = forms.CharField(max_length=30)
    Password = forms.CharField(max_length=30)
    First_Name = forms.CharField(max_length=30)
    Surname = forms.CharField(max_length=30)
    Email = forms.EmailField(max_length=100)
    Question = forms.CharField(max_length=150)
    Answer = forms.CharField(max_length=50)


class ReviewForm(forms.Form):
	comment = forms.CharField(max_length=300,widget=forms.Textarea)

class CoverSheetForm(forms.Form):
    aec_protocol = forms.CharField(max_length=200, strip=False)
    protocol_title = forms.CharField(max_length=200, strip=False)
    start_date = forms.DateField()
    cheif_investigator = forms.CharField(max_length=30)
    cheif_investigator_phone = forms.CharField(max_length=10)
    emergency_investigator = forms.CharField(max_length=30)
    emergency_investigator_phone = forms.CharField(max_length=10)
    monitor_1 = forms.CharField(max_length=30)
    monitor_1_phone = forms.CharField(max_length=10)
    monitor_2 = forms.CharField(max_length=30)
    monitor_2_phone = forms.CharField(max_length=10)
    monitor_3 = forms.CharField(max_length=30)
    monitor_3_phone = forms.CharField(max_length=10)
    supervision = forms.BooleanField()
    euthanasia_person = forms.CharField(max_length=30)
    euthanasia_phone = forms.CharField(max_length=10)
    other_experts = forms.CharField(max_length=30)
    other_experts_phone = forms.CharField(max_length=10)
    # species/phenotype/issues
    species_phenotype_issues = forms.CharField(max_length=30)
    # MONITORING CRITERIA AND SCORING
    scrit = forms.CharField()
    pcrit = forms.CharField()

    # monitory frequency
    monitoring_frequency = forms.CharField(max_length=200)
    # type of recording sheet
    typeofsheet = forms.ChoiceField()
    other_description = forms.CharField()
    protocol_title = forms.CharField(max_length=200, strip=False)
    start_date = forms.DateTimeField()
    cheif_investigator = forms.CharField(max_length=30)
    cheif_investigator_phone = forms.CharField(max_length=10)
    emergency_investigator = forms.CharField(max_length=30)
    emergency_investigator_phone = forms.CharField(max_length=10)
    monitor_1 = forms.CharField(max_length=30)
    monitor_1_phone = forms.CharField(max_length=10)
    monitor_2 = forms.CharField(max_length=30)
    monitor_2_phone = forms.CharField(max_length=10)
    monitor_3 = forms.CharField(max_length=30)
    monitor_3_phone = forms.CharField(max_length=10)
    supervision = forms.BooleanField()
    euthanasia_person = forms.CharField(max_length=30)
    euthanasia_phone = forms.CharField(max_length=10)
    other_experts = forms.CharField(max_length=30)
    other_experts_phone = forms.CharField(max_length=10)
    #species/phenotype/issues
    species_phenotype_issues = forms.CharField(max_length=30)
    #MONITORING CRITERIA AND SCORING
    actions1a = forms.CharField()
    actions1b = forms.CharField()
    actions2a = forms.CharField()
    actions2b = forms.CharField()
    actions3a = forms.CharField()
    actions3b = forms.CharField()
    actions4a = forms.CharField()
    actions4b = forms.CharField()
    additional = forms.CharField()
    #AEC interventions
    aec1 = forms.CharField()
    aec2 = forms.CharField()
    aec3 = forms.CharField()
    aec4 = forms.CharField()
    aec5 = forms.CharField()
    aec6 = forms.CharField()
    aec7 = forms.CharField()
    aec8 = forms.CharField()
    #monitory frequency
    monitoring_frequency = forms.CharField(max_length=200,widget=forms.Textarea)
    #type of recording sheet
    general = forms.BooleanField()	
    anasthesia = forms.BooleanField()
    post_proc = forms.BooleanField()
    other = forms.BooleanField()
    other_description = forms.CharField()


class EditProfileForm(forms.Form):
    First_Name = forms.CharField(max_length=30)
    Surname = forms.CharField(max_length=30)
    Email = forms.EmailField(max_length=100)


class QuestionForm(forms.Form):
    Username = forms.CharField(max_length=30,  widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    Question = forms.CharField(max_length=150,  widget=forms.TextInput(attrs={'readonly': 'readonly', 'size': 80}))
    Answer = forms.CharField(max_length=50)
    Password = forms.CharField(max_length=30)

class CriteriaTemplateForm(forms.Form):
    name = forms.CharField()
    scrit = forms.CharField()

animalwellbeing/views.py
from django.shortcuts import render, redirect
# will improve later down the line
from .forms import *
from .models import *
from django.db.models import Q
from django.urls import reverse

# user authentication
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import PasswordChangeForm

# downloading files
from django.http import FileResponse
import subprocess
import json
# Create your views here.

from .additional_func import standardise_keys


def index(request):
	context = {}
	if request.user.is_authenticated and (
			request.user.is_superuser or Researchers.objects.filter(user=request.user).exists()):
		context = {
			'isResearcher': not request.user.is_superuser,
			'user': request.user if request.user.is_superuser else Researchers.objects.get(user=request.user),
			'templates': CoverSheetFormModel.objects.all().order_by(
				'-updated_at') if request.user.is_superuser else CoverSheetFormModel.objects.filter(
				creator=Researchers.objects.get(user=request.user)).order_by('-updated_at')
		}
	return redirect('/awb/accounts/login') if not request.user.is_authenticated else render(request,
																							'animalwellbeing/welcome.html',
																							context)


def logout_view(request):
	logout(request)
	return redirect('/awb/')


@login_required
@user_passes_test(lambda u: u.is_superuser)
def requests_approval_admin(request):
	context = {
		'user': request.user if request.user.is_superuser else Researchers.objects.get(user=request.user),
		'templates': CoverSheetFormModel.objects.filter(request_lodged=True).order_by('-updated_at')
	}
	return render(request, 'animalwellbeing/requests.html', context)


@login_required
def view_coversheet(request, coversheet_id):
	coversheetmodel = None
	try:
		# improve this later on
		coversheetmodel = CoverSheetFormModel.objects.get(pk=coversheet_id)
		return render(request, 'animalwellbeing/view_coversheet.html', coversheetmodel.all_data)
	except CoverSheetFormModel.DoesNotExist:
		return redirect('/awb/')


def password_validators(password):
	if len(password) < 6 or \
			all(char.isdigit() for char in password) or \
			all(char.isalpha() for char in password) or \
			all(char.islower() for char in password):
		return True


@login_required
def request_approval(request, coversheet_id):
	coversheetmodel = None
	try:
		if request.user.is_superuser:
			coversheetmodel = CoverSheetFormModel.objects.get(pk=coversheet_id)
		else:
			coversheetmodel = CoverSheetFormModel.objects.get(pk=coversheet_id,
															  creator=Researchers.objects.get(user=request.user))
		coversheetmodel.request_lodged = True
		coversheetmodel.save()
	except CoverSheetFormModel.DoesNotExist:
		pass
	return redirect('/awb/panel/{}/'.format(coversheet_id))


def create_researcher(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		username = form['Username'].value()
		password = form['Password'].value()
		email = form['Email'].value()
		surname = form['Surname'].value()
		firstname = form['First_Name'].value()
		input_question = form['Question'].value()
		input_answer = form['Answer'].value()
		try:
			user = User.objects.create_user(
					username=username,
					password=password,
					email=email,
					is_active=False
				)
			user.save()
			new_researcher = Researchers.objects.create(
					user=user,
					surname=surname,
					firstname=firstname,
					email=email
				)
			new_researcher.save()
			question = Question.objects.create(
					user_Q=username,
					Question=input_question,
					Answer=input_answer
				)
			question.save()
			print('Successfully created researcher')
		except:
			pass
		return redirect('/awb/')
	usernames = json.dumps([user.username for user in User.objects.all()])
	return render(request, 'animalwellbeing/signup.html',{'usernames':usernames})

def user_activation(request):
	context = {
		'is_active': User.objects.filter(is_active=False)
	}
	return render(request, 'animalwellbeing/activation.html', context)

@login_required
@user_passes_test(lambda u: u.is_superuser)
def activate(request, username):
	try:
		user_need_activation = User.objects.get(username=username)
		user_need_activation.is_active = True
		user_need_activation.save()
		context = {
			'is_active': User.objects.filter(is_active=False)
		}
		return render(request, 'animalwellbeing/activation.html', context)
	except User.DoesNotExist:
		return redirect('/awb/')
		


@login_required
def view_profile(request):
	user = request.user
	args = {'user': user}
	context = {'researchers_infor': Researchers.objects.get(user=user),
			   'user': request.user if request.user.is_superuser else Researchers.objects.get(user=request.user)}
	return render(request, 'animalwellbeing/profile.html', context, args)


@login_required
def edit_profile(request):
	if request.method == 'POST':
		form = EditProfileForm(request.POST)
		if form.is_valid():
			First_Name = form.cleaned_data['First_Name']
			Surname = form.cleaned_data['Surname']
			email = form.cleaned_data['Email']
			r = Researchers.objects.get(user=request.user)
			r.firstname = First_Name
			r.surname = Surname
			r.save()
			u = User.objects.get(username=request.user)
			u.email = email
			u.save()
			return redirect(reverse('awb:view_profile'))
	else:
		data = {'First_Name': Researchers.objects.get(user=request.user).firstname,
				'Surname': Researchers.objects.get(user=request.user).surname,
				'Email': User.objects.get(username=request.user).email}
		form = EditProfileForm(initial=data)
		args = {'form': form,
				'user': request.user if request.user.is_superuser else Researchers.objects.get(user=request.user)}
		return render(request, 'animalwellbeing/edit_profile.html', args)


@login_required
def change_password(request):
	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)

		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			return redirect(reverse('awb:view_profile'))

	else:
		form = PasswordChangeForm(user=request.user)

	args = {'form': form, 'user': request.user if request.user.is_superuser else Researchers.objects.get(user=request.user)}
	return render(request, 'animalwellbeing/change_password.html', args)


def get_username(request):
	if request.method == 'POST':
		username = request.POST.get('search_name')
		exist = User.objects.filter(username=username)
		if exist and username:
			data = {'Question': Question.objects.get(user_Q=username).Question,
					'Username': username}
			form = QuestionForm(initial=data)
			args = {'form': form}
			return render(request, 'animalwellbeing/validate_question.html', args)
		elif not exist:
			return render(request, 'animalwellbeing/get_username.html', {'attempt': True})
	return render(request, 'animalwellbeing/get_username.html')


def validate_question(request):
	if request.method == "POST":
		form = QuestionForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['Username']
			answer = form.cleaned_data['Answer']
			password = form.cleaned_data['Password']
			a = password_validators(password)
			if a:
				data = {'Question': Question.objects.get(user_Q=username).Question,
						'Username': username}
				form = QuestionForm(initial=data)
				data = {'first': "Your password must contain at least 6 characters",
						'second': "Your password must contain at least 1 uppercase letter",
						'third': "Your password must contain at least 1 number and 1 letter",
						'form': form}
				return render(request, 'animalwellbeing/validate_question.html', data)

			if answer == Question.objects.get(user_Q=username).Answer:
				user = User.objects.get(username=username)
				user.set_password(password)
				user.save()
				return redirect('/awb/accounts/login')
			else:
				data = {'Question': Question.objects.get(user_Q=username).Question,
						'Username': username}
				form = QuestionForm(initial=data)
				args = {'form': form, 'answer_wrong': "Your answer was incorrect, please try again"}
				return render(request, 'animalwellbeing/validate_question.html', args)
	return redirect('awb:get_username')


@login_required
def panel(request, coversheet_id):
	coversheetmodel = None
	try:
		if request.user.is_superuser:
			coversheetmodel = CoverSheetFormModel.objects.get(pk=coversheet_id)
		else:
			coversheetmodel = CoverSheetFormModel.objects.get(pk=coversheet_id,
															  creator=Researchers.objects.get(user=request.user))
	except CoverSheetFormModel.DoesNotExist:
		return redirect('/awb/')

	if request.method == 'POST':
		form = ReviewForm(request.POST)
		msg = Message.objects.create(message=form['comment'].value(), date=datetime.datetime.now(),
									 coversheet=coversheetmodel, author=request.user.username)
		coversheetmodel.request_lodged = False
		coversheetmodel.save()
		msg.save()

	return render(request, 'animalwellbeing/coversheetpanel.html', {
		'coversheet': coversheetmodel,
		'user': request.user if request.user.is_superuser else Researchers.objects.get(user=request.user),
		'messagelist': Message.objects.filter(coversheet=coversheetmodel).order_by('-date'),
	})


@login_required
def cancel_request(request, coversheet_id):
	coversheetmodel = None
	try:
		if request.user.is_superuser:
			coversheetmodel = CoverSheetFormModel.objects.get(pk=coversheet_id)
		else:
			coversheetmodel = CoverSheetFormModel.objects.get(pk=coversheet_id,
															  creator=Researchers.objects.get(user=request.user))
	except CoverSheetFormModel.DoesNotExist:
		return redirect('/awb/')
	coversheetmodel.request_lodged = False
	coversheetmodel.save()
	return redirect('/awb/panel/{}/'.format(coversheet_id))


@login_required
def edit_form(request, coversheet_id):
	criteriamodel = None
	coversheetmodel = None
	try:
		if request.user.is_superuser:

testsite/testsite/animalwellbeing/templates/animalwellbeing/actvation.html
{% extends "./index.html" %}
{% block title %} {% if request.user.is_superuser %} {{user.username}} {% else %} {{user.firstname}} {% endif %}'s Profile {% endblock %}
{% block content %}
    <div class="container-fluid">
        <h1> Hey {% if request.user.is_superuser %} {{user.username}} {% else %} {{user.firstname}} {% endif %} </h1>
        <p class="text-muted"><i> {% if request.user.is_superuser %} Superuser {% else %}Researcher {% endif %} </i></p>
        <p>
            Welcome to UWA's animal well being app
        </p>
    </div>
    <br>
    <br>

    <table class="table">
        <thead>
          <tr>
			  <th scope="col">Name</th>
              <th scope="col">Created</th>
			  <th scope="col">Status</th>
              <th scope="col">Activate</th>
		  </tr>
        </thead>
        <tbody>
            {% for user in is_active %}
                <tr>
                    <td>{{user.username}}</td>
                    <td>{{user.date_joined}}</td>
                    <td>{{ user.is_active }}</td>
                    <td><a href={% url 'awb:activate' name=user.username %}><button type="button" class="btn btn-link">Activate</button></a> </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

testsite/testsite/animalwellbeing/templates/animalwellbeing/create_criteria.html
{% extends "./index.html" %}
{% block title %}Create Criteria{% endblock %}
{% block content %}
<div class="container">
	<br>
<div class = "card">
	<div class="card-header">Create Criteria</div>
	<div class="card-body">
		<form method="POST">
			{% csrf_token %}
			<h1>Criteria Name</h1>
			<input type="text" name=""><br>
			<h1>Zero Discritor</h1>
			<textarea cols="30" rows="4" placeholder="Zero Descriptor" style="width:100%;"></textarea>
			<h1>One Discritor</h1>
			<textarea cols="30" rows="4" placeholder="Criteria Description" style="width:100%;"></textarea>
			<h1>Two Discritor</h1>
			<textarea cols="30" rows="4" placeholder="Criteria Description" style="width:100%;"></textarea>
			<button class="btn btn btn-outline-success btn-block" type="submit">Create Criterea</button>

		</form>
	</div>
</div>
{% endblock %}

testsite/testsite/animalwellbeing/templates/animalwellbeing/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<style>
	html,
body {
  height: 100%;
}

body {
  display: -ms-flexbox;
  display: flex;
  -ms-flex-align: center;
  align-items: center;
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #f5f5f5;
}


.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}
.form-signin .checkbox {
  font-weight: 400;
}
.form-signin .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
</style>
<body class="text-center">
	<form class="form-signin" method="post" >
      {% csrf_token %}
      {% load static %}
      <!-- animalwellbeing/paw-print-rooweb-clipart.png -->
      <h1 class="h3 mb-3 font-weight-normal"> Telos</h1>
        <h5 class="mt-5 mb-3 font-weight-normal"> Respecting the unique nature of each animal species</h5>
			<img ="mb-4" src={% static 'animalwellbeing/rat.png' %} alt="" width="308" height="140">
      <br>
      <br>
			<input type="text" class="form-control" name="Username" placeholder="Username" required>
       <input type="password"  class="form-control" name="Password" placeholder="Password" required>
       <p class="mt-5 mb-3 text-muted"> Please Sign In to continue</p>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <br>
        <div>
        <a href={% url 'awb:create_researcher' %} > <button type="button" class="btn btn-light btn-link">Create Researcher</button></a>
        </div>
        <div>
          <a href={% url 'awb:get_username' %}>Forgot Password?</a>
        </div>
      {%if has_attempted %}
          <p class="mt-5 mb-3 text-muted"> Incorect username or password. If you don't have a account click  <a href={% url 'awb:create_researcher' %} >here </a> </p>
      {% elif activation %}
          <p class="mt-5 mb-3 text-muted"> New account need to be approval by Admin</p>
      <br>
      <br>
      {% endif %}
       </form>
       
</body>
</html>

testsite/testsite/animalwellbeing/templates/animalwellbeing/view_coversheet.html
{% extends "./index.html" %}
{% block title %} Cover Sheet {% endblock %}
{% block content %}
<style>
	table, th, td {
	   border: 1px solid black;
	}
	th, td {
	    padding: 15px;
	    text-align: left;
	}
</style>
<div class="container-fluid">
	<br>
	<h1>{{sheet.contact_details.protocol_title}}</h1>
	<!-- <p>Sheet contents (for testing): {{sheet}}</p> -->
	<a href={% url 'awb:edit_cs' sheetid %}>Edit this sheet</a>
	<h2>Contact Information</h2>
	<table>
		<tr><th>Title:</th><td>{{sheet.contact_details.protocol_title}}</td></tr>
		<tr><th>Start Date:</th><td>{{sheet.contact_details.start_date}}</td></tr>
		<tr><th>Chief Investigator:</th><td>{{sheet.contact_details.chief_investigator.0}}</td><td>Ph. {{sheet.contact_details.chief_investigator.1}}</td></tr>
		<tr><th>Emergency Contact:</th><td>{{sheet.contact_details.emergency_contact.0}}</td><td>Ph. {{sheet.contact_details.emergency_contact.1}}</td></tr>
		<tr><th>Monitoring Officer 1:</th><td>{{sheet.contact_details.monitor_2.0}}</td><td>Ph. {{sheet.contact_details.monitor_1.1}}</td></tr>
		<tr><th>Monitoring Officer 2:</th><td>{{sheet.contact_details.monitor_2.0}}</td><td>Ph. {{sheet.contact_details.monitor_2.1}}</td></tr>
		<tr><th>Monitoring Officer 3:</th><td>{{sheet.contact_details.monitor_3.0}}</td><td>Ph. {{sheet.contact_details.monitor_3.1}}</td></tr>
		<tr><th>Officer in charge of Euthanization:</th><td>{{sheet.contact_details.euth_officer.0}}</td><td>Ph. {{sheet.contact_details.euth_officer.1}}</td></tr>
		<tr><th>Other officer:</th><td>{{sheet.contact_details.other.0}}</td><td>Ph. {{sheet.contact_details.other.1}}</td></tr>
	</table>
	<br>
	<h2>Protocol Details</h2>
	<table>
		<tr><th>Species:</th><td>{{sheet.species_phenotype_issues.species}}</td></tr>
		<tr><th>Monitoring Criteria: </th><td>To Be Completed</td></tr>
	</table>
	</div>
{% endblock %}

testsite/testsite/animalwellbeing/templates/animalwellbeing/welcome.html
{% extends "./index.html" %}
{% block title %} {% if request.user.is_superuser %} {{user.username}} {% else %} {{user.firstname}} {% endif %}'s Profile {% endblock %}
{% block content %}

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

<script type="text/javascript" src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

<div class="container-fluid">

	<h1> Hey {% if request.user.is_superuser %} {{user.username}} {% else %} {{user.firstname}} {% endif %} </h1>
	<p class="text-muted"><i> {% if request.user.is_superuser %} Superuser {% else %}Researcher {% endif %} </i></p>
	<p>
		Welcome to Telos
	</p>


	{% if templates or results%}
<!-- 	{%if request.user.is_superuser %}
	 <form method="get" action="{% url 'awb:search' %}">
            <label>Author: </label>
			<input type="text" class="w-auto" name="author" placeholder="search_by_author" >
            <label>Project-name: </label>
            <input type="text" class="w-auto" name="projectName" placeholder="search_project_by_name" >
            <label>Date: </label>
            <input type="date" class="w-auto" name="date" placeholder="Year-month-day" >
		    <button type="submit">Search</button>
	 </form>
	{% endif %} -->
	<div class="card">
	<div class="card-header">{% if request.user.is_superuser %} All Coversheets {% else %}{{user.firstname}}'s Coversheets {% endif %}</div>
	<div class="card-body">
	{% if isResearcher %}
		<a href={% url 'awb:createcoversheet' %}> <button type="button" class="btn btn-primary">Create CoverSheet form</button></a>
		<br>
	{% else %}
		<a href={% url 'awb:cs_requests' %}> <button type="button" class="btn btn-primary">Coversheet Review Requests</button></a>
	{% endif %}
	<table id="myTable" class="table table-striped table-bordered" style="table-layout:fixed;
    width:100%;">
		<thead>
		  <tr>
			<th scope="col">Name</th>
			<th scope="col">Created</th>
			{% if not isResearcher %}
			<th scope="col">Author</th>
			{% endif %}
			<th scope="col">Approval</th>
			
		  </tr>
		</thead>
		<tbody>

        {% if results %}
        {% for templ in results %}
		  <tr>
			<td>{{templ.name}}</td>
			<td>{{templ.created_at}}</td>
			<td>{{templ.creator.firstname}}</td>
              {% if not isResearcher %}
			<td> <font color="red">Unapproved</font></td>
              {% endif %}
		  </tr>
		  {% endfor %}
        {% else %}
			<h2>{{Message}}</h2>
		{% endif %}

			{% for templ in templates %}
		  <tr>
			<td scope="row"> <a href={% url 'awb:panel_cs' templ.pk %}>{{templ.name}}</a>  </td>
			<td>{{templ.created_at}}</td>
			{% if not isResearcher %}
			<td>{{templ.creator.firstname}}</td>
			{% endif %}
			<td> {% if templ.approved %} <font color="green"> Approved </font> {% else %} <font color="red"> Unapproved</font> {% endif %}</td>
		  </tr>
		  {% endfor %}
		</tbody>
	  </table>
	  </div>
	  	</div>
	  {% else %}
	  	{% if isResearcher %}
		<a href={% url 'awb:createcoversheet' %}> <button type="button" class="btn btn-primary">Create CoverSheet form</button></a>
		<br>
		<p class="text-muted"><i>You have no coversheets. Get started in creating your own coversheet using the button above. </i></p>
		{% endif %}
	  {% endif %}
	  	</div>
	<script type="text/javascript">
		$(document).ready( function () {
    	$('#myTable').DataTable();
		});
	</script>
{% endblock %}